name: contracosta #formerly starry_base
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - scipy
  - matplotlib
  - astropy
  - astroquery # from conda-forge channel
  - beautifulsoup4
  - requests
  - tqdm
  - pandas
  - bokeh # optional, needed for interact
  - jupyter # optional
  - ipython # optional
  - seaborn # optional
  - scikit-learn # optional
  - scikit-image # optional
  - pytest-cov # for documentation and testing
  - pytest-remotedata # for documentation and testing
  - pytest-runner # for documentation and testing
  - sphinx # for documentation and testing
  - sphinx_rtd_theme # for documentation and testing
  - nbsphinx # for documentation and testing
  - numpydoc # for documentation and testing
  - sphinx-automodapi # for documentation and testing
  - graphviz
  - ghp-import
  - pybind11
  - cython
  - pylint
  - flake8
  - autopep8
  - pep8
  - black
  - fast-histogram
  - specutils
  - h5py
  - pip
  - pip:
    - twisted # optional
    - mkl-random # optional
    - astroml # optional
    - corner
    - emcee
    # - wget
    - celerite2
    - exoplanet
    - importlib_resources
    - fleck
    - batman-package